"use client";

import {
  ChatCircle,
  Lightning,
  Users,
  CurrencyDollar,
  GraduationCap,
  Monitor,
  Code,
  MagicWand,
  DeviceMobile,
  Desktop,
  Laptop,
  Devices,
  FileText,
  File,
  FilePdf,
  FileDoc,
  FileCode,
  Database,
  CloudArrowUp,
  HardDrives,
  MagnifyingGlass,
  Globe,
  CaretDown,
  CaretRight,
  Gear,
  Wrench,
  Bug,
  Terminal,
} from "@phosphor-icons/react";
import { DiavanaIcon } from "./DiavanaIcon";

// Icon mapping för kategorier med Phosphor Icons
export const CategoryIcons = {
  chat: ChatCircle,
  lightning: Lightning,
  users: Users,
  dollar: CurrencyDollar,
  education: GraduationCap,
  monitor: Monitor,
  code: Code,
  magic: MagicWand,
  mobile: DeviceMobile,
  desktop: Desktop,
  laptop: Laptop,
  devices: Devices,
  documents: FileText,
  files: File,
  pdf: FilePdf,
  word: FileDoc,
  coding: FileCode,
  database: Database,
  cloud: CloudArrowUp,
  hardware: HardDrives,
  search: MagnifyingGlass,
  web: Globe,
  settings: Gear,
  tools: Wrench,
  debugging: Bug,
  terminal: Terminal,
  diavana: DiavanaIcon,
};

// Exportera individuella ikoner för direkt användning
export {
  ChatCircle,
  Lightning,
  Users,
  CurrencyDollar,
  GraduationCap,
  Monitor,
  Code,
  MagicWand,
  DeviceMobile,
  Desktop,
  Laptop,
  Devices,
  FileText,
  File,
  FilePdf,
  FileDoc,
  FileCode,
  Database,
  CloudArrowUp,
  HardDrives,
  MagnifyingGlass,
  Globe,
  CaretDown,
  CaretRight,
  Gear,
  Wrench,
  Bug,
  Terminal,
  DiavanaIcon,
};
