name: Build and Deploy Support Frontend to K3s

on:
  push:
    branches:
      - main
      - dev

env:
  REGISTRY: docker.io/titusystem
  IMAGE_NAME: support-frontend
  NAMESPACE: support-frontend
  DEPLOYMENT: support-frontend
  CONTAINER_NAME: support-frontend
  ENVIRONMENT: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Image
        run: |
          IMAGE_SHA_TAG="${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA}"
          IMAGE_LATEST_TAG="${REGISTRY}/${IMAGE_NAME}:${ENVIRONMENT}-latest"
          
          echo "Building Docker image with tags:"
          echo "$IMAGE_SHA_TAG"
          echo "$IMAGE_LATEST_TAG"
          
          docker build -t "$IMAGE_SHA_TAG" -t "$IMAGE_LATEST_TAG" .
          docker push "$IMAGE_SHA_TAG"
          docker push "$IMAGE_LATEST_TAG"

  deploy:
    runs-on: [self-hosted, k3s-deploy]
    needs: build_and_push
    steps:
      - name: Deploy K3s
        env:
          KUBECONFIG: /home/deploy/.kube/config
        run: |
          IMAGE_SHA_TAG="${REGISTRY}/${IMAGE_NAME}:${GITHUB_SHA}"
          kubectl -n "${NAMESPACE}" set image deployment/${DEPLOYMENT} ${CONTAINER_NAME}="${IMAGE_SHA_TAG}"
          kubectl -n "${NAMESPACE}" rollout status deployment/${DEPLOYMENT} --timeout=180s